name       : python-pytz
version    : '2019.2'
release    : 9
source     :
    - https://pypi.python.org/packages/source/p/pytz/pytz-2019.2.tar.gz : 26c0b32e437e54a18161324a2fca3c4b9846b74a8dccddd843113109e1116b32
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        for f in pytz/tests/*.py; do
            %python_test $f
        done
    popd
    pushd $PKG_BUILD_DIR/py3build
        for f in pytz/tests/*.py; do
            %python3_test $f
        done
    popd
