name       : python-pytz
version    : 2017.2
release    : 3
source     :
    - https://pypi.python.org/packages/a4/09/c47e57fc9c7062b4e83b075d418800d322caa87ec0ac21e6308bd3a2d519/pytz-2017.2.zip : f5c056e8f62d45ba8215e5cb8f50dfccb198b4b9fbea8500674f3443e4689589
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
