name       : python-pytz
version    : 2018.7
release    : 6
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2018.7.tar.gz : 31cb35c89bd7d333cd32c5f278fca91b523b0834369e757f4c5641ea252236ca
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        for f in pytz/tests/*.py; do
            %python_test $f
        done
    popd
    pushd $PKG_BUILD_DIR/py3build
        for f in pytz/tests/*.py; do
            %python3_test $f
        done
    popd
