name       : python-pytz
version    : '2018.9'
release    : 7
source     :
    - https://pypi.python.org/packages/source/p/pytz/pytz-2018.9.tar.gz : d5f05e487007e29e03409f9398d074e158d920d36eb82eaf66fb1136b0c5374c
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        for f in pytz/tests/*.py; do
            %python_test $f
        done
    popd
    pushd $PKG_BUILD_DIR/py3build
        for f in pytz/tests/*.py; do
            %python3_test $f
        done
    popd
