name       : python-pytz
version    : '2020.1'
release    : 12
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2020.1.tar.gz : c35965d010ce31b23eeb663ed3cc8c906275d6be1a34393a1d73a41febf4a048
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-pytest
    - python-setuptools
setup      : |
    %patch -p1 < $pkgfiles/use-system-zoneinfo.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    rm -rf $installdir/usr/lib/python%python2_version%/site-packages/pytz/zoneinfo
    %python3_install
    rm -rf $installdir/usr/lib/python%python3_version%/site-packages/pytz/zoneinfo
check      : |
    %python_test pytest
    %python3_test pytest3
