name       : python-pytz
version    : 2018.4
release    : 4
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2018.4.tar.gz : c06425302f2cf668f1bba7a0a03f3c1d34d4ebeef2c72003da308b3947c7f749
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        export PYTHONPATH=$PWD
        for f in pytz/tests/*.py; do
            python $f
        done
    popd
    pushd $PKG_BUILD_DIR/py3build
        export PYTHONPATH=$PWD
        for f in pytz/tests/*.py; do
            python3 $f
        done
    popd
