name       : python-pytz
version    : '2022.7'
release    : 21
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2022.7.tar.gz : 7ccfae7b4b2c067464a6733c6261673fdb8fd1be905460396b97a073e9fa683a
homepage   : http://pythonhosted.org/pytz
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-pytest
setup      : |
    %patch -p1 < $pkgfiles/use-system-zoneinfo.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/lib/python%python3_version%/site-packages/pytz/zoneinfo
check      : |
    %python3_test pytest3
