name       : python-pytz
version    : 2016.4
release    : 1
source     :
    - https://pypi.python.org/packages/f4/7d/7c0c85e9c64a75dde11bc9d3e1adc4e09a42ce7cdb873baffa1598118709/pytz-2016.4.tar.bz2 : ee7c751544e35a7b7fb5e3fb25a49dade37d51e70a93e5107f10575d7102c311
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
