name       : python-pytz
version    : '2021.1'
release    : 15
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2021.1.tar.gz : 83a4a90894bf38e243cf052c8b58f381bfe9a7a483f6a9cab140bc7f702ac4da
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-pytest
    - python-setuptools
setup      : |
    %patch -p1 < $pkgfiles/use-system-zoneinfo.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    rm -rf $installdir/usr/lib/python%python2_version%/site-packages/pytz/zoneinfo
    %python3_install
    rm -rf $installdir/usr/lib/python%python3_version%/site-packages/pytz/zoneinfo
check      : |
    %python_test pytest
    %python3_test pytest3
