name       : python-pytz
version    : '2018.5'
release    : 5
source     :
    - https://pypi.io/packages/source/p/pytz/pytz-2018.5.tar.gz : ffb9ef1de172603304d9d2819af6f5ece76f2e85ec10692a524dd876e72bf277
license    : MIT
component  : programming.python
summary    : World timezone definitions, modern and historical
description: |
    World timezone definitions, modern and historical
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        export PYTHONPATH=$PWD
        for f in pytz/tests/*.py; do
            python $f
        done
    popd
    pushd $PKG_BUILD_DIR/py3build
        export PYTHONPATH=$PWD
        for f in pytz/tests/*.py; do
            python3 $f
        done
    popd
